version: '3.9'
services:
  moodist:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/remvze/moodist
    logging:
      options:
        max-size: 1g
    restart: always
    ports:
      - '8080:8080'
